#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will help perform the steps to configure an
#      application connector. You need to follow these steps in order.
#      The steps are as follows:
#      - Verify that the target F5 device is running v13 or greater
#      - Verify that the F5 device is licensed for iAppsLX and App Connector.
#      - Provision all desired modules including iRulesLX. This playbook will
#        provision iRulesLX
#      - This playbook will enable App Connector.
#      - This playbook will create the two neccessary virtual servers for App 
#        Connector. 
#         -- A port 443 vip with the appropriate clientssl profile, a tcp and
#            an HTTP profile. Create the child profiles before running this
#            playbook. This vip will NOT have a pool.
#         -- Create a port 80 vip with a pool with no members.
# 

- name: Provision modules
  hosts: 10.0.0.174
  connection: local

  tasks: 
   - name: Provisioning iRulesLX
     bigip_provision:
         module: "ilx"
         level: "nominal"
         server: "10.0.0.160"
         user: "admin"
         password: "admin"
         validate_certs: "no"
     delegate_to: localhost

   - name: Enabling App Connector
     raw: touch /var/config/rest/iapps/enable

   - name: Creating port 443 Vip with no pool.
       bigip_virtual_server:
           description: "Vip that the ACproxy will connect to"
           destination: "20.20.20.108"
           password: "admin"
           name: "ACProxy_vs"
           port: "443"
           server: "10.0.0.160"
           snat: "Automap"
           user: "admin"
           all_profiles:
               - "http"
               - "clientssl"
           validate_certs: "no"
       delegate_to: localhost

   - name: Creating the cloud_pool
       bigip_pool:
           lb_method: "round-robin"
           monitors: "ac_http"
           name: "cloud_pool"
           password: "admin"
           server: "10.0.0.160"
           slow_ramp_time: "120"
           user: "admin"
           validate_certs: "no"
       delegate_to: localhost

   - name: Create the cloud vip
       bigip_virtual_server:
           description: "cloud-vip"
           destination: "20.20.20.108"
           password: "admin"
           name: "cloud_vip"
           pool: "cloud_pool"
           port: "80"
           server: "10.0.0.160"
           snat: "Automap"
           user: "admin"
           all_profiles:
               - "http"
           validate_certs: "no"
       delegate_to: localhost



