---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will enable iAppsLX and install the application
#      services extension (AS3) 
#      The steps are as follows:
#      - Verify that the target F5 device is running v13 or greater
#      - Provision all desired modules including iRulesLX. This playbook will
#        provision iRulesLX if you are running Ansible 2.4. 
#        NOTICE: Be sure you have staged the AS3 rpm package in the 
#        ~/ansible/playbooks directory.
#        See documentation at: http://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/
#        See prerequisites at: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/prereqs.html
#        See AS3 example declarations by navigating to https://<management ip>/mgmt/shared/appsvcs/delare?show=expanded

- name: Configuring bigip for AS3 extension
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    server: "192.168.0.24"
    setup_user: "admin"
    setup_pass: "Kenkar@00"
    rpm_package: "f5-appsvcs-3.8.0-3.noarch.rpm"
  tasks:
 
   - name: Enabling iAppsLX
     bigip_command:
         commands: run /util bash -c 'touch /var/config/rest/iapps/enable'
         server: "{{ server }}"
         password: "{{ setup_pass }}"
         user: "{{ setup_user }}"
         validate_certs: "no"
     delegate_to: localhost

     #   - name: pushing rpm package to bigip
     #copy: src=/home/mlowcher/ansible/playbooks/f5-appsvcs-3.8.0-3.noarch.rpm dest=/var/config/rest/downloads/
#     copy: src=/home/mlowcher/ansible/playbooks/f5-appsvcs-3.8.0-3.noarch.rpm dest=/opt/.sdm/var/config/rest/downloads/ mode 775

   - name: Add an iAppLX package
     bigip_iapplx_package:
         package: "/mnt/c/Users/lowcher/AnsibleFiles/f5-appsvcs-3.8.0-3.noarch.rpm"
         password: "{{setup_pass}}"
         server: "{{ server }}"
         state: present
         user: "{{setup_user}}"
         validate_certs: "no"
     delegate_to: localhost
