#!/usr/bin/ansible-playbook
---
      
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      short_description: This playbook will add allowed urls
#      to an ASM policy. 
#      Do the following curl command piped to jq from the CLI of the F5.
#      curl -sku admin:admin https://localhost/mgmt/tm/asm/policies | jq .items 


- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Get facts from CSV file
    csv_to_facts:
      src: ./files/asm_add_urls.csv

  - name: Adding urls to an ASM policy 
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/asm/policies/UOBxa66WFloQwonbHg3Rlw/urls"
      body: '{"protocol":"http","name":"{{item.allowed_url}}"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"
