#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will enable the application Connector
#      service center. 
#      The steps are as follows:
#      - Verify that the target F5 device is running v13 or greater
#      - Verify that the F5 device is licensed for App Connector.
#      - Provision all desired modules including iRulesLX. This playbook will
#        provision iRulesLX if you are running Ansible 2.4 and you uncomment 
#        the provisioning module below.
#      - This playbook will enable App Connector.
#        NOTICE: Be sure you have staged the files in the ~/ansible/playbooks
#        directory as described in the "Ansible Orchestration for Application
#        Connector deployment guide located at https://github.com/mlowcher61
#      - After running this playbook perform the manual steps described in the 
#        deployment guide prior to running the appconnector_vips playbook. 

- name: Configuring App Connecter service center
  hosts: 10.0.0.40
  connection: local
  gather_facts: no
  vars:
    server1: "10.0.0.40"
    setup_user: "admin"
    setup_pass: "admin"
    app_connector: "app-connector-1.0.1-52.0.noarch.rpm"

  tasks:

   - name: Add an iAppLX package
     bigip_iapplx_package:
         package: "./files/{{app_connector}}"
         password: "{{setup_pass}}"
         server: "{{ server1 }}"
         state: "present"
         user: "{{setup_user}}"
         validate_certs: "no"
     delegate_to: localhost
