#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will set the DNS
#      settings. state: "absent" will remove the settings. 

- name: Connecting...
  hosts: "10.0.0.157"
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    bigip: "10.0.0.157"

  tasks:
    - name: run multiple commands and evaluate the output
      bigip_command:
        commands:
          - show sys version
          - list ltm virtual
        wait_for:
          - result[0] contains BIG-IP
          - result[1] contains mobileiron
        server: "{{bigip}}"
        user: "{{setup_user}}"
        password: "{{setup_pass}}"
        validate_certs: "no"
      delegate_to: localhost
