#!/usr/bin/ansible-playbook 
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a child ssl persistence profile with default ssl 
#      persistence profile as the parent. Enable "matchAcross*" as desired.
#      Edit the "vars" below accordingly.

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    appliance: "10.0.0.160"
    child_ssl: "app1_ssl_persist"
 
  tasks:
  - name: Create a child ssl persistence profile
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/ltm/persistence/ssl"
      body: '{"name": "{{child_ssl}}","defaultsFrom": "/Common/ssl","matchAcrossPools": "disabled","matchAcrossServices": "disabled","matchAcrossVirtuals": "disabled"}' 
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
