#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will config-sync the failover-sync group named SyncFail.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    appliance: "10.0.0.175"

  tasks:

  - name: Config Sync
    icontrol_install_config:
      uri: "mgmt/tm/cm/"
      body: '{"command":"run","utilCmdArgs":"config-sync to-group SyncFail"}'
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"

