---
#!/usr/bin/ansible-playbook
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a user.
#

- name: Create user
  hosts: localhost
  connection: local
  gather_facts: no


  tasks:
      - name: Add the user 'johnd' with a specific role on the provided partition
        bigip_user:
#            login_host: "10.0.0.157"
            login_user: "admin"
            login_password: "admin"
            name: "johnd"
            comment: "John Doe"
            role: "admin"
            state: "present"
            validate_certs: "no"
        delegate_to: localhost
        tags:
            - create

      - name: Get the facts for the admin user
        bigip_user_facts:
            server: "10.0.0.157"
            user: "admin"
            password: "admin"
            name: "johnd"
            validate_certs: "no"
        delegate_to: localhost
        tags:
            - read

      - name: Set the admin user's shell
        bigip_user:
            login_host: "10.0.0.157"
            login_user: "admin"
            login_password: "admin"
            name: "admin"
            shell: "tmsh"
            validate_certs: "no"
        delegate_to: localhost
        tags:
            - shell
