---
- hosts: 52.35.125.165
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: Kenkar@00
    bigip: bigip[1]

  tasks:

   - name: Resetting to default config
     bigip_command:
      server: 52.35.125.165
      user: "{{username}}"
      password: "{{password}}"
      commands:
      - load sys config default
      validate_certs: false
     delegate_to: localhost

