#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will delete a vip and it's redirect vip.
#      Requires Ansible 2.3 or higher

- name: Delete a VIP, pool, members and nodes
  hosts: 10.0.0.160
  connection: local
  gather_facts: no
  vars:
    appliance: "10.0.0.160"
    setup_user: "admin"
    setup_pass: "admin"
    vipname: "my_vip"
    http_redirect: "my_redirect"



  tasks:

  - name: Delete vip "{{vipname}}"
    bigip_virtual_server:
        description: "{{vipname}}"
        destination: "{{vip_ip}}"
        password: "{{setup_pass}}"
        name: "{{vipname}}"
        server: "{{appliance}}"
        user: "{{setup_user}}"
        state: "absent"
        validate_certs: "no"
    delegate_to: localhost

  - name: Delete the redirect virtual server
    bigip_virtual_server:
        description: "Redirect Virtual Server"
        server: "{{appliance}}"
        user: "{{setup_user}}"
        password: "{{setup_pass}}"
        name: "{{http_redirect}}"
        destination: "{{vip_ip}}"
        port: 80
        state: "absent"
        validate_certs: "no"
    delegate_to: localhost
