---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create an HA configuration
#      on two newly licensed devices.
#      search and replace ":s%/search_string/replace_string/g"

- name: Set up a single bigip
  hosts: bigip[0]
  gather_facts: false

  vars:
   bigip1: 192.168.0.24
   hostname1: f5.home.com 
   external_vlan: external_vlan
   internal_vlan: internal_vlan
   external_self_name: external_self
   internal_self_name: internal_self
   external_self_1: 20.20.20.20
   internal_self_1: 10.10.10.10
   ext_netmask: 255.255.255.0
   int_netmask: 255.255.255.0
   external_tag: 20
   internal_tag: 10
   name_server_1: 64.65.64.65
   name_server_2: 8.8.8.8
   setup_user: admin
   setup_pass: Kenkar@00
   state: present
# Change the state above to "absent" to remove object(s)

  tasks:
  
  - name: Change device name of BIGIP1
    bigip_hostname:
      hostname: "{{ hostname1 }}"
      password: "{{ setup_pass }}"
      server: "{{ bigip1 }}"
      user: "{{ setup_user }}"
      validate_certs: no
    delegate_to: localhost

  - name: Disabling the setup utility
    bigip_sys_global:
     gui_setup: "no"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     password: "{{ setup_pass }}"
     validate_certs: no
    delegate_to: localhost

  - name: Creating external vlan
    bigip_vlan:
     name: "{{ external_vlan }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     password: "{{ setup_pass }}"
     tag: "{{ external_tag }}"
     validate_certs: no
    delegate_to: localhost

  - name: Creating internal vlan
    bigip_vlan:
     name: "{{ internal_vlan }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     password: "{{ setup_pass }}"
     tag: "{{ internal_tag }}"
     validate_certs: no
    delegate_to: localhost

  - name: Adding external vlan as untagged to interface 1.1 
    bigip_vlan:
     untagged_interfaces: 1.1
     name: "{{ external_vlan }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     password: "{{ setup_pass }}"
     validate_certs: no
    delegate_to: localhost
    
  - name: Adding internal vlan as untagged to interface 1.2 
    bigip_vlan:
     untagged_interfaces: 1.2
     name: "{{ internal_vlan }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     password: "{{ setup_pass }}"
     validate_certs: no
    delegate_to: localhost

  - name: Creating external self ip 
    bigip_selfip:
     name: "{{ external_self_name }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     pass: "{{ setup_pass }}"
     address: "{{ external_self_1 }}"
     vlan: "{{ external_vlan }}"
     traffic_group: "traffic-group-local-only"
     netmask: "{{ ext_netmask }}"
     validate_certs: no
    delegate_to: localhost


  - name: Creating internal self ip
    bigip_selfip:
     name: "{{ internal_self_name }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     pass: "{{ setup_pass }}"
     address: "{{ internal_self_1 }}"
     vlan: "{{ internal_vlan }}"
     traffic_group: "traffic-group-local-only"
     netmask: "{{ int_netmask }}"
     validate_certs: no
    delegate_to: localhost
#  -name: Configuring DNS servers
#   bigip_device_dns:
#     name_servers:
#         - "{{ name_server_1 }}"
#         - "{{ name_server_2 }}"
#     search:
#         - localdomain
#         - lab.local
#     state: present
#     server: "{{ bigip1 }}"
#     user: "{{ setup_user }}"
#     pass: "{{ setup_pass }}"
#     validate_certs: no
#    delegate_to: localhost
#    with_items:
#           - server: "{{ bigip1 }}"
#           - server: "{{ bigip2 }}"

  - name: Configuring NTP servers
    bigip_device_ntp:
     ntp_servers:
        - "192.0.2.23"
     timezone: "America/Chicago"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     pass: "{{ setup_pass }}"
     state: present
     validate_certs: "no"
    delegate_to: localhost

  - name: Set the banner for the SSHD service from a file
    bigip_device_sshd:
     banner: enabled
     banner_text: "{{ lookup('file', './SSHD-banner.txt') }}"
     server: "{{ bigip1 }}"
     user: "{{ setup_user }}"
     pass: "{{ setup_pass }}"
     validate_certs: "no"
    delegate_to: localhost
