---
- name: F5 Integration with Netbox for VS Address
  hosts: aws-F5
  connection: local
  vars_files:
    - vars/vars.yml
  tasks:
  - name: get available IP from netbox IPAM
    uri:
      url: "{{ NETBOX_URL }}"
      method: POST
      body_format: json
      body: { "description": "created by ansible script to deploy a Virtual Server on F5 BIG-IP: {{ F5_SERVER }}" }
      status_code: 201
      headers:
        Authorization: "Token {{ NETBOX_TOKEN }}"
        Accept: application/json
    register: IP_json

  - name: set fact
    set_fact:
      VS_address: "{{ IP_json|json_query('json.address') }}"
  - debug: var=IP_json
  - debug: var=VS_address
  - name: VIP
    bigip_virtual_server:
        server: "{{ F5_SERVER }}"
        user: admin
        password: "{{ F5_PASSWORD }}"
        state: present
        name: "ansible_vs_{{ VS_address | replace('/24', '') }}"
        destination: "{{ VS_address }}"
        port: 80
        pool: "my-pool"
        snat: Automap
        description: Ansible Virtual Server
        all_profiles:
            - http
        validate_certs: "no"
    delegate_to: localhost
