#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will perform the steps to configure
#      ACProxy on a linux machine in the cloud
#      A deployment guide can be found at https://github.com/mlowcher61
#      The steps are as follows:
#      - Spin up an instance of Linux Ubuntu in your cloud.
#      - Perform steps neccessary to have Ansible ssh to the linux host
#      - Verify that the linux host can access the internet
#      - Put ACproxy code into your working directory in Ansible host (~/ansible/playbooks)
#      - Put docker.list file in the same directory.
#       (See Ansible Orchestration for App Connector)

- name: Creating a docker system running two instances of ACproxy
  hosts: acproxy
  sudo: yes
  connection: local
  gather_facts: no
  vars:
    appliance: "supnetops"
    setup_user: "admin"
    setup_pass: "admin"
    ACproxy_code: "f5-acproxy-1.0.1-build.52.tgz"
    ACproxy_start: "acproxy:1.0.1-build.52"

  tasks:

   - name: Updating apt...
     raw: sudo apt-get update

   - name: Pull down docker key
     raw: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

   - name: Copying docker.list file to linux host
     copy: src=~/ansible/playbooks/docker.list dest=/etc/apt/sources.list.d/

   - name: Updating apt...
     raw: sudo apt-get update

   - name: Installing Docker on Linux host...
     raw: sudo apt-get install docker-engine --assume-yes

   - name: Download super netops and run and begin session
     raw: sudo docker run -p 8080:80 -p 2222:22 -it f5devcentral/f5-super-netops-container:base

