#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      state=absent will delete if it exist and do nothing if it doesn't.
#      service_down_action, decides what to do when a node goes down.
#      possible options are: none, reset, drop or reselect.

- name: Connecting...
  hosts: 10.0.0.175
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    name: irule1
    bigip: "10.0.0.175"


  tasks:
  tasks:
    - name: Pushing irule "{{ name }}"
      bigip_irule:
          content: "{{ lookup('template', 'irule1.tcl') }}"
          state: "present"
          name: "{{ name }}"
          user: "{{setup_user}}"
          password: "{{setup_pass}}"
          server: "{{bigip}}"   
          validate_certs: "no"
      delegate_to: localhost
