#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create the virtual servers
#      needed on the application connector service center.
#
#      - This playbook will copy the necessary files to the F5
#        NOTICE: Be sure you have staged the files in the ~/ansible/playbooks
#        directory as described in the "Ansible Orchestration for Application
#        Connector deployment guide located at https://github.com/mlowcher61
#      - This playbook will create the two neccessary virtual servers for App 
#        Connector service center. 
#         -- A port 443 vip with the appropriate clientssl profile, a tcp and
#            an HTTP profile. Create the child profiles before running this
#            playbook. This vip will NOT have a pool.
#         -- Create a port 80 vip with a pool with no members.
#      - Edit the "vars" below to match your environment. "appliance" is the
#        management ip address of the F5. 
#      - The ACproxy ip is the public ip address that clients will connect to 
#        when accessing your application(s). You will need to run this playbook
#        for ever application that you deploy.
#      - The cloud ip is the public ip address that the AC_proxies will connect
#        back to.
#      - Before running this playbook, create the clientssl profile you will use
#        to offload SSL/TLS and change the value "clientssl" under vars to the 
#        correct name. Such as "myapp_clientssl" 
#      - It is also a best practice to create an http profile per application
#        such as "myapp_http_profile" and edit it accordingly under "vars"

- name: Setting up DO
  hosts: 192.168.0.17
  connection: local
  gather_facts: no
  vars:
    appliance: "192.168.0.17"
    setup_user: "admin"
    setup_pass: "Kenkar@00"
    package: "f5-declarative-onboarding-1.5.0-11.noarch.rpm"

  tasks: 

     - name: Enabling iAppsLX
       bigip_command:
           commands: run /util bash -c 'touch /var/config/rest/iapps/enable'
           provider:
             server: "{{ appliance }}"
             password: "{{ setup_pass }}"
             user: "{{ setup_user }}"
             validate_certs: "no"
       delegate_to: localhost

     - name: Installing DO rpm 
       bigip_lx_package:
           package: "{{ package }}"
           provider:
             password: "{{ setup_pass }}"
             server: "{{ appliance }}"
             user: "{{ setup_user }}"
             validate_certs: "no"
       delegate_to: localhost
