---
- name: Starting Layer 2 configuration
  hosts: bigip[0]
  gather_facts: false
  vars_files:
    - network_config_vars.yml

  tasks:

  - name: Create a route domain
    bigip_routedomain:
        id: "{{item.id}}"
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        server: "{{ inventory_hostname }}"
        state: "present"
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Configure VLANs on the BIG-IP
    bigip_vlan:
     server: "{{ inventory_hostname }}"
     user: "{{ username }}"
     password: "{{ password }}"
     validate_certs: False
     name: "{{ item.name }}"
     tag: "{{ item.tag }}"
     tagged_interface: "{{ item.interface }}"
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Set VLANs on route domain 1
    bigip_routedomain:
        id: 1
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        server: "{{ inventory_hostname }}"
        state: "present"
        vlans: 
            - vlan9
            - vlan11
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Set VLANs on route domain 2
    bigip_routedomain:
        id: 2
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        server: "{{ inventory_hostname }}"
        state: "present"
        vlans:
            - vlan10
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Set VLANs on route domain 3
    bigip_routedomain:
        id: 3
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        server: "{{ inventory_hostname }}"
        state: "present"
        vlans:
            - vlan12
    with_items: "{{ vlan_information }}"
    delegate_to: localhost


  - name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     server: "{{ inventory_hostname }}"
     user: "{{ username }}"
     password: "{{ password }}"
     validate_certs: False
     name: "{{ item.name }}"
     address: "{{ item.address }}"
     netmask: "{{ item.netmask }}"
     route_domain: "{{item.id}}"
     vlan: "{{ item.vlan }}"
     traffic_group: "{{ item.traffic_group }}"
    with_items: "{{ selfip_information }}"
    delegate_to: localhost
