---
#
#      Copyright (c) 2016 World Wide Technology, Inc. 
#      All rights reserved. 
#
#      author: Mark Wall  World Wide Technology
#      short_description: Automation of F5 Initial Setup 
#      description: Importing configuration via CSV files to automate initial configuration of F5.
#                   This playbook will read a CSV file and perform initial F5 setup steps leaving a 
#                   running active/standby pair.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    server: "192.168.0.17"      
    setup_user: "admin"
    setup_pass: "Kenkar@00"
    
  tasks:

    - name: Deploying DO                
      raw: 
#  - name: Deploying DO
#    icontrol_install_config: 
#     method: "_post_"
#     uri: "/mgmt/shared/declarative-onboarding"
#     body: '{"name":"{{DO.json}}"'
#     host: "{{server}}"
#     username: "{{setup_user}}"
#     password: "{{setup_pass}}"
