#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will disable the setup wizard in the GUI.

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    appliance: "10.0.0.176"
  tasks:

  - name: Enable ASM on vip
    icontrol_install_config:
      uri: "/mgmt/tm/ltm/virtual/~Common~app1_vs/profiles"
      method: "_post_"
      body: '{"context":"all","name":"websecurity"}'
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"


  - name: Apply ASM policy to vip
    icontrol_install_config:
      uri: "/mgmt/tm/ltm/virtual/~Common~app1_vs/policies"
      method:  "_post_"
      body: '{"name":"/~Common~/marktest"}'
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"




