#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a pool with two members
#      attached to an ssl offload vip. It will also create a redirect vip
#      to make sure people get to the 443 vip. 
#      Create your child profiles and monitors first and change the names
#      in this playbook accordingly. The profiles used for the redirect
#      vip can remain unchanged.

- name: Create a VIP, pool, pool members and nodes
  hosts: 10.0.0.160
  connection: local

  tasks:
      - name: Create a pool
        bigip_pool:
            lb_method: "ratio_member"
            monitors: "http"
            name: "web_pool"
            password: "admin"
            server: "10.0.0.160"
            slow_ramp_time: "120"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create node1
        bigip_node:
            host: "10.10.10.10"
            name: "node-1"
            password: "admin"
            server: "10.0.0.160"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create node2
        bigip_node:
            host: "10.10.10.20"
            name: "node-2"
            password: "admin"
            server: "10.0.0.160"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost

      - name: Add nodes to pool
        bigip_pool_member:
            description: "webserver-1"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "admin"
            pool: "web_pool"
            port: "80"
            server: "10.0.0.160"
            user: "admin"
            validate_certs: "no"
        delegate_to: localhost
        with_items:
            - host: "10.10.10.10"
              name: "node-1"
            - host: "10.10.10.20"
              name: "node-2"

      - name: Create a VIP
        bigip_virtual_server:
            description: "foo-vip"
            destination: "20.20.20.108"
            password: "admin"
            name: "vip-1"
            pool: "web_pool"
            port: "443"
            server: "10.0.0.160"
            snat: "Automap"
            user: "admin"
            all_profiles:
                - "http"
                - "clientssl"
            validate_certs: "no"
        delegate_to: localhost

      - name: Create a redirect virtual server
        bigip_virtual_server:
            description: "Redirect Virtual Server"
            server: "10.0.0.160"
            user: "admin"
            password: "admin"
            name: "http_redirect"
            destination: "20.20.20.108" 
            port: 80
            all_profiles:
                - http
            all_rules:
                - _sys_https_redirect   
            validate_certs: "no" 
        delegate_to: localhost
