#!/usr/bin/ansible-playbook gtmpool.yml
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will read a CSV file for variables and create a GTM pool. This playbook assumes that vlans and self-ips are already in place. Listeners, datacenters and server objects must also already be configured. If gslb will be configured on the standby unit as well, uncomment the config-sync session at the bottom of this playbook.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Calling gslb.csv file for variables
    csv_to_facts:
      src: ./files/gslb.csv

  - name: Adding first GTM pool
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/pool/a"
      body: '{"name":"{{item.app1_pool}}"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

  - name: Adding members to "{{item.app1_pool}}"
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/pool/a/~Common~firstapp_pool/members"
      body: '{"name":"gtm-ltm-dallas:mytest_vs","members":"~Common~gtm-ltm-dallas/mytest_vs"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

