#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will license two F5 devices.
#

- name: Connecting...
  hosts: localhost
  gather_facts: false

  vars:
   appliance1: 10.0.0.185
   appliance2: 10.0.0.186
   setup_user: admin
   setup_pass: admin
   regkey1: WHDQH-HZNMC-BQCBP-HPBIS-ZWOXMGA
   regkey2: WHDQH-HZNMC-BQCBP-HPBIS-ZWOXMGA

  tasks:
   - name: Licensing the first device
     icontrol_install_config:
       uri: "/mgmt/tm/util/bash"
       body: '{ "command":"run”,"utilCmdArgs":"-c ’/usr/local/bin/SOAPLicenseClient --interactive  --basekey "{{regkey1}}"’”}'
       host: "{{appliance1}}"
       username: "{{setup_user}}"
       password: "{{setup_pass}}"


   - name: Licensing the second device
     icontrol_install_config:
       uri: "/mgmt/tm/util/bash"
       body: '{ "command":"run”,"utilCmdArgs":"-c ’/usr/local/bin/SOAPLicenseClient --interactive  --basekey "{{regkey2}}"’”}'
       host: "{{appliance2}}"
       username: "{{setup_user}}"
       password: "{{setup_pass}}"



