#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will read a CSV file for variables and create a gslb configuration. This playbook assumes that vlans and self-ips are already in place. If gslb will be configured on the standby unit as well, uncomment the config-sync session at the bottom of this playbook.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Create a pool
    csv_to_facts:
      src: ./files/gslb.csv

  - name: Addng a UDP GTM listener
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/gtm/listener"
      body: '{"name":"{{item.udp_name}}","address":"{{item.address}}","ipProtocol":"udp"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    
  - name: Adding a TCP GTM listener
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/gtm/listener"
      body: '{"name":"{{item.tcp_name}}","address":"{{item.address}}","ipProtocol":"tcp"}'     
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"

  - name: Defining the "{{datacenter1}}" datacenter
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/datacenter"
      body: '{"name":"{{item.datacenter1}}","location":"{{item.datacenter1}}"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"

  - name: Defining the "{{datacenter2}}" datacenter
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/datacenter"
      body: '{"name":"{{item.datacenter2}}","location":"{{item.datacenter2}}"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"
