#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will run a series of playbooks
#      from top down.  
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Pulling variables from add_app.csv
    csv_to_facts:
      src: ./files/add_app.csv

  - name: Adding pool
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/ltm/pool"
      body: '{"name":"{{item.poolname}}","loadBalancingMode":"least-connections-member","monitor":"/Common/http","members":"{{item.member}}"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    
  - name: Adding a VIP
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/ltm/virtual"
      body: '{"name":"{{item.vipname}}","destination":"{{item.vip_ip}}","ipProtocol":"{{item.protocol}}","pool":"{{item.poolname}}","sourceAddressTranslation": { "type":"automap" },"profiles": [ { "name":"/Common/tcp-lan-optimized", "context":"clientside" },{ "name":"/Common/tcp-wan-optimized", "context":"serverside" },"/Common/http"]}'     
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"

  - name: Config Sync
    icontrol_install_config:
      uri: "mgmt/tm/cm/"
      body: '{"command":"run","utilCmdArgs":"config-sync to-group SyncFail"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"
    
