#!/usr/bin/ansible-playbook BBBBBBBBBBB
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will read a CSV file for variables and create a gslb configuration. This playbook assumes that vlans and self-ips are already in place. If gslb will be configured on the standby unit as well, uncomment the config-sync session at the bottom of this playbook.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Calling gslb.csv file for variables
    csv_to_facts:
      src: ./files/gslb.csv

  - name: Adding first server object
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/server"
      body: '{"name":"{{item.server_object1}}","datacenter":"{{item.datacenter1}}","monitor":"/Common/bigip","product":"single-bigip","addresses":[{"name":"{{item.server_object1_self}}","deviceName":"{{item.deviceName1}}"}]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

  - name: Adding a virtual server to the "{{item.server_object1}}" server object
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/server/~Common~gtm-ltm-dallas/virtual-servers"
      body: '{"name":"{{item.vip1_name}}","destination":"{{item.vip1_ipport}}","monitor":"/Common/gateway_icmp"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

  - name: Adding second server object
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/server"
      body: '{"name":"{{item.server_object2}}","datacenter":"{{item.datacenter2}}","monitor":"/Common/bigip","product":"single-bigip","addresses":[{"name":"{{item.server_object2_self}}","deviceName":"{{item.deviceName2}}"}]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

  - name: Adding a virtual server to the "{{item.server_object2}}" server object
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/gtm/server/~Common~gtm-ltm-secaucus/virtual-servers"
      body: '{"name":"{{item.vip2_name}}","destination":"{{item.vip2_ipport}}","monitor":"/Common/gateway_icmp"}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"

    
