#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will read create a clientssl profile. 
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    appliance: "10.0.0.164"

  tasks:

  - name: Create the explicit serverssl profile
    icontrol_install_config: 
      method: "_post_"
      uri: "/mgmt/tm/ltm/profile/server-ssl"
      body: '{"name":"explicit-serverssl","sslForwardProxy": "enabled","sslForwardProxyBypass": "enabled"}'
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
