#!/usr/bin/ansible-playbook gtmpool.yml
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will read a CSV file for variables and create an SWG explicit configuration.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    appliance: "10.0.0.164"
    
  tasks:

  - name: Adding an explicit httpS VIP
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/ltm/virtual"
      body: '{"name":"explicit-https-vs","destination":"0.0.0.0:443","ipProtocol":"tcp","sourceAddressTranslation": { "type":"automap" },"vlans": [ "/Common/explicit-tunnel"],"profiles": [ { "name":"/Common/tcp-lan-optimized", "context":"clientside" },{ "name":"/Common/tcp-wan-optimized", "context":"serverside" },"/Common/http","/Common/explicit-clientssl","/Common/explicit-serverssl"]}'
      host: "{{appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"


