#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a wildcard ip-forwarding
#      virtual server. You can add the following to control which vlans
#      to listen on. The default is all vlans.
#      enabled_vlans:
#          - /Common/desired vlan(s)
#      Change snat: "none" to "Automap" if snatting is required.
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~NOTICE~~~~~~~~~~~~~~~~~~~~~~~
#      As of now ip-forwarding vips using the bigip_virtual_server module
#      is not supported. This playbook is on the back burner until that 
#      functionality is provided.  

- name: F5 Setup
  hosts: 10.0.0.160
  connection: local

  tasks: 
   - name: Create a wildcard ip-forwarding virtual
       bigip_virtual_server:
           description: "Wildcard ip-forwarding virtual"
           destination: "0.0.0.0:0"
           password: "admin"
           name: "Wildcard-forwarder"
           port: "*"
           server: "10.0.0.160"
           snat: "none"
           user: "admin"
           validate_certs: "no"
       delegate_to: localhost




