---
#
#      Copyright (c) 2017 F5 Networks 
#      All rights reserved. 
#
#      author: Mark Lowcher  
#      short_description: Creating an Egress and Ingress trunk with two interfaces in each 
#      description: Importing configuration via CSV file 
#                   This playbook will read a CSV file to pull the variables for trunk 
#                   creation.
#

- name: F5 Setup
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    
  tasks:
  - name: Get facts from CSV file
    csv_to_facts:
      src: ./files/trunks.csv

  - name: Create Egress LACP Trunk on Device .15
    icontrol_install_config: 
      uri: "/mgmt/tm/net/trunk"
      body: '{"name":"{{item.trunk}}","lacp":"enabled","lacpMode":"active","lacpTimeout":"short","interfaces":["{{item.trunk_int_1}}","{{item.trunk_int_2}}"]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"

  - name: Create Ingress LACP Trunk on Device .15
    icontrol_install_config:
      uri: "/mgmt/tm/net/trunk"
      body: '{"name":"{{item.trunk2}}","lacp":"enabled","lacpMode":"active","lacpTimeout":"short","interfaces":["{{item.trunk2_int_1}}","{{item.trunk2_int_2}}"]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "yes"

  - name: Create Egress LACP Trunk on Device .16
    icontrol_install_config:
      uri: "/mgmt/tm/net/trunk"
      body: '{"name":"{{item.trunk}}","lacp":"enabled","lacpMode":"active","lacpTimeout":"short","interfaces":["{{item.trunk_int_1}}","{{item.trunk_int_2}}"]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "no"

  - name: Create Ingress LACP Trunk on Device .16
    icontrol_install_config:
      uri: "/mgmt/tm/net/trunk"
      body: '{"name":"{{item.trunk2}}","lacp":"enabled","lacpMode":"active","lacpTimeout":"short","interfaces":["{{item.trunk2_int_1}}","{{item.trunk2_int_2}}"]}'
      host: "{{item.appliance}}"
      username: "{{setup_user}}"
      password: "{{setup_pass}}"
    with_items: "{{spreadsheet}}"
    when: item.primary == "no"

